### ISSUE TITLE
Carrier-pigeon does not work on Ruby 1.8.5

### ISSUE THREAD

**Issue by jamtur01** [portertech/carrier-pigeon#4]
(This is totally not your fault - it's because Ruby 1.8.5 sucks - I thought it was important to note here in case someone else stumbled across it).

On Ruby 1.8.5 the `instance_variable_defined?' method does not exist and addressable/uri uses this method. Hence on Ruby 1.8.5 you get:

```
undefined method `instance_variable_defined?' for #<Addressable::URI:0xb6c9cdfc>
```

**Comment by portertech** [comment]
Perhaps we should state Ruby >= 1.8.7 in the README and call it a day :)

**Comment by jamtur01** [comment]
Let me see if I can monkey-patch something either here or upstream

**Comment by portertech** [comment]
Doesn't look like there has ever been a related issue filed for addressable, a monkey patch for old rubies could be thrown in here.

**Comment by jamtur01** [comment]
I logged this upstream.

**Comment by portertech** [comment]
@jamtur01 Awesome :) https://github.com/portertech/carrier-pigeon/blob/master/carrier-pigeon.gemspec#L15
